package iso4217

type Currency struct {
	Alpha3      string
	Numeric    int
	MinorUnits int
	Name       string
}

var currenciesByAlpha3 = map[string]Currency{
	"AFN": {Alpha3: "AFN", Numeric: 971, MinorUnits: 2, Name: "Afghani"},
	"EUR": {Alpha3: "EUR", Numeric: 978, MinorUnits: 2, Name: "Euro"},
	"ALL": {Alpha3: "ALL", Numeric: 8, MinorUnits: 2, Name: "Lek"},
	"DZD": {Alpha3: "DZD", Numeric: 12, MinorUnits: 2, Name: "Algerian Dinar"},
	"USD": {Alpha3: "USD", Numeric: 840, MinorUnits: 2, Name: "US Dollar"},
	"AOA": {Alpha3: "AOA", Numeric: 973, MinorUnits: 2, Name: "Kwanza"},
	"XCD": {Alpha3: "XCD", Numeric: 951, MinorUnits: 2, Name: "East Caribbean Dollar"},
	"XAD": {Alpha3: "XAD", Numeric: 396, MinorUnits: 2, Name: "Arab Accounting Dinar"},
	"ARS": {Alpha3: "ARS", Numeric: 32, MinorUnits: 2, Name: "Argentine Peso"},
	"AMD": {Alpha3: "AMD", Numeric: 51, MinorUnits: 2, Name: "Armenian Dram"},
	"AWG": {Alpha3: "AWG", Numeric: 533, MinorUnits: 2, Name: "Aruban Florin"},
	"AUD": {Alpha3: "AUD", Numeric: 36, MinorUnits: 2, Name: "Australian Dollar"},
	"AZN": {Alpha3: "AZN", Numeric: 944, MinorUnits: 2, Name: "Azerbaijan Manat"},
	"BSD": {Alpha3: "BSD", Numeric: 44, MinorUnits: 2, Name: "Bahamian Dollar"},
	"BHD": {Alpha3: "BHD", Numeric: 48, MinorUnits: 3, Name: "Bahraini Dinar"},
	"BDT": {Alpha3: "BDT", Numeric: 50, MinorUnits: 2, Name: "Taka"},
	"BBD": {Alpha3: "BBD", Numeric: 52, MinorUnits: 2, Name: "Barbados Dollar"},
	"BYN": {Alpha3: "BYN", Numeric: 933, MinorUnits: 2, Name: "Belarusian Ruble"},
	"BZD": {Alpha3: "BZD", Numeric: 84, MinorUnits: 2, Name: "Belize Dollar"},
	"XOF": {Alpha3: "XOF", Numeric: 952, MinorUnits: 0, Name: "CFA Franc BCEAO"},
	"BMD": {Alpha3: "BMD", Numeric: 60, MinorUnits: 2, Name: "Bermudian Dollar"},
	"INR": {Alpha3: "INR", Numeric: 356, MinorUnits: 2, Name: "Indian Rupee"},
	"BTN": {Alpha3: "BTN", Numeric: 64, MinorUnits: 2, Name: "Ngultrum"},
	"BOB": {Alpha3: "BOB", Numeric: 68, MinorUnits: 2, Name: "Boliviano"},
	"BOV": {Alpha3: "BOV", Numeric: 984, MinorUnits: 2, Name: "Mvdol"},
	"BAM": {Alpha3: "BAM", Numeric: 977, MinorUnits: 2, Name: "Convertible Mark"},
	"BWP": {Alpha3: "BWP", Numeric: 72, MinorUnits: 2, Name: "Pula"},
	"NOK": {Alpha3: "NOK", Numeric: 578, MinorUnits: 2, Name: "Norwegian Krone"},
	"BRL": {Alpha3: "BRL", Numeric: 986, MinorUnits: 2, Name: "Brazilian Real"},
	"BND": {Alpha3: "BND", Numeric: 96, MinorUnits: 2, Name: "Brunei Dollar"},
	"BGN": {Alpha3: "BGN", Numeric: 975, MinorUnits: 2, Name: "Bulgarian Lev"},
	"BIF": {Alpha3: "BIF", Numeric: 108, MinorUnits: 0, Name: "Burundi Franc"},
	"CVE": {Alpha3: "CVE", Numeric: 132, MinorUnits: 2, Name: "Cabo Verde Escudo"},
	"KHR": {Alpha3: "KHR", Numeric: 116, MinorUnits: 2, Name: "Riel"},
	"XAF": {Alpha3: "XAF", Numeric: 950, MinorUnits: 0, Name: "CFA Franc BEAC"},
	"CAD": {Alpha3: "CAD", Numeric: 124, MinorUnits: 2, Name: "Canadian Dollar"},
	"KYD": {Alpha3: "KYD", Numeric: 136, MinorUnits: 2, Name: "Cayman Islands Dollar"},
	"CLP": {Alpha3: "CLP", Numeric: 152, MinorUnits: 0, Name: "Chilean Peso"},
	"CLF": {Alpha3: "CLF", Numeric: 990, MinorUnits: 4, Name: "Unidad de Fomento"},
	"CNY": {Alpha3: "CNY", Numeric: 156, MinorUnits: 2, Name: "Yuan Renminbi"},
	"COP": {Alpha3: "COP", Numeric: 170, MinorUnits: 2, Name: "Colombian Peso"},
	"COU": {Alpha3: "COU", Numeric: 970, MinorUnits: 2, Name: "Unidad de Valor Real"},
	"KMF": {Alpha3: "KMF", Numeric: 174, MinorUnits: 0, Name: "Comorian Franc "},
	"CDF": {Alpha3: "CDF", Numeric: 976, MinorUnits: 2, Name: "Congolese Franc"},
	"NZD": {Alpha3: "NZD", Numeric: 554, MinorUnits: 2, Name: "New Zealand Dollar"},
	"CRC": {Alpha3: "CRC", Numeric: 188, MinorUnits: 2, Name: "Costa Rican Colon"},
	"CUP": {Alpha3: "CUP", Numeric: 192, MinorUnits: 2, Name: "Cuban Peso"},
	"XCG": {Alpha3: "XCG", Numeric: 532, MinorUnits: 2, Name: "Caribbean Guilder"},
	"CZK": {Alpha3: "CZK", Numeric: 203, MinorUnits: 2, Name: "Czech Koruna"},
	"DKK": {Alpha3: "DKK", Numeric: 208, MinorUnits: 2, Name: "Danish Krone"},
	"DJF": {Alpha3: "DJF", Numeric: 262, MinorUnits: 0, Name: "Djibouti Franc"},
	"DOP": {Alpha3: "DOP", Numeric: 214, MinorUnits: 2, Name: "Dominican Peso"},
	"EGP": {Alpha3: "EGP", Numeric: 818, MinorUnits: 2, Name: "Egyptian Pound"},
	"SVC": {Alpha3: "SVC", Numeric: 222, MinorUnits: 2, Name: "El Salvador Colon"},
	"ERN": {Alpha3: "ERN", Numeric: 232, MinorUnits: 2, Name: "Nakfa"},
	"SZL": {Alpha3: "SZL", Numeric: 748, MinorUnits: 2, Name: "Lilangeni"},
	"ETB": {Alpha3: "ETB", Numeric: 230, MinorUnits: 2, Name: "Ethiopian Birr"},
	"FKP": {Alpha3: "FKP", Numeric: 238, MinorUnits: 2, Name: "Falkland Islands Pound"},
	"FJD": {Alpha3: "FJD", Numeric: 242, MinorUnits: 2, Name: "Fiji Dollar"},
	"XPF": {Alpha3: "XPF", Numeric: 953, MinorUnits: 0, Name: "CFP Franc"},
	"GMD": {Alpha3: "GMD", Numeric: 270, MinorUnits: 2, Name: "Dalasi"},
	"GEL": {Alpha3: "GEL", Numeric: 981, MinorUnits: 2, Name: "Lari"},
	"GHS": {Alpha3: "GHS", Numeric: 936, MinorUnits: 2, Name: "Ghana Cedi"},
	"GIP": {Alpha3: "GIP", Numeric: 292, MinorUnits: 2, Name: "Gibraltar Pound"},
	"GTQ": {Alpha3: "GTQ", Numeric: 320, MinorUnits: 2, Name: "Quetzal"},
	"GBP": {Alpha3: "GBP", Numeric: 826, MinorUnits: 2, Name: "Pound Sterling"},
	"GNF": {Alpha3: "GNF", Numeric: 324, MinorUnits: 0, Name: "Guinean Franc"},
	"GYD": {Alpha3: "GYD", Numeric: 328, MinorUnits: 2, Name: "Guyana Dollar"},
	"HTG": {Alpha3: "HTG", Numeric: 332, MinorUnits: 2, Name: "Gourde"},
	"HNL": {Alpha3: "HNL", Numeric: 340, MinorUnits: 2, Name: "Lempira"},
	"HKD": {Alpha3: "HKD", Numeric: 344, MinorUnits: 2, Name: "Hong Kong Dollar"},
	"HUF": {Alpha3: "HUF", Numeric: 348, MinorUnits: 2, Name: "Forint"},
	"ISK": {Alpha3: "ISK", Numeric: 352, MinorUnits: 0, Name: "Iceland Krona"},
	"IDR": {Alpha3: "IDR", Numeric: 360, MinorUnits: 2, Name: "Rupiah"},
	"XDR": {Alpha3: "XDR", Numeric: 960, MinorUnits: -1, Name: "SDR (Special Drawing Right)"},
	"IRR": {Alpha3: "IRR", Numeric: 364, MinorUnits: 2, Name: "Iranian Rial"},
	"IQD": {Alpha3: "IQD", Numeric: 368, MinorUnits: 3, Name: "Iraqi Dinar"},
	"ILS": {Alpha3: "ILS", Numeric: 376, MinorUnits: 2, Name: "New Israeli Sheqel"},
	"JMD": {Alpha3: "JMD", Numeric: 388, MinorUnits: 2, Name: "Jamaican Dollar"},
	"JPY": {Alpha3: "JPY", Numeric: 392, MinorUnits: 0, Name: "Yen"},
	"JOD": {Alpha3: "JOD", Numeric: 400, MinorUnits: 3, Name: "Jordanian Dinar"},
	"KZT": {Alpha3: "KZT", Numeric: 398, MinorUnits: 2, Name: "Tenge"},
	"KES": {Alpha3: "KES", Numeric: 404, MinorUnits: 2, Name: "Kenyan Shilling"},
	"KPW": {Alpha3: "KPW", Numeric: 408, MinorUnits: 2, Name: "North Korean Won"},
	"KRW": {Alpha3: "KRW", Numeric: 410, MinorUnits: 0, Name: "Won"},
	"KWD": {Alpha3: "KWD", Numeric: 414, MinorUnits: 3, Name: "Kuwaiti Dinar"},
	"KGS": {Alpha3: "KGS", Numeric: 417, MinorUnits: 2, Name: "Som"},
	"LAK": {Alpha3: "LAK", Numeric: 418, MinorUnits: 2, Name: "Lao Kip"},
	"LBP": {Alpha3: "LBP", Numeric: 422, MinorUnits: 2, Name: "Lebanese Pound"},
	"LSL": {Alpha3: "LSL", Numeric: 426, MinorUnits: 2, Name: "Loti"},
	"ZAR": {Alpha3: "ZAR", Numeric: 710, MinorUnits: 2, Name: "Rand"},
	"LRD": {Alpha3: "LRD", Numeric: 430, MinorUnits: 2, Name: "Liberian Dollar"},
	"LYD": {Alpha3: "LYD", Numeric: 434, MinorUnits: 3, Name: "Libyan Dinar"},
	"CHF": {Alpha3: "CHF", Numeric: 756, MinorUnits: 2, Name: "Swiss Franc"},
	"MOP": {Alpha3: "MOP", Numeric: 446, MinorUnits: 2, Name: "Pataca"},
	"MKD": {Alpha3: "MKD", Numeric: 807, MinorUnits: 2, Name: "Denar"},
	"MGA": {Alpha3: "MGA", Numeric: 969, MinorUnits: 2, Name: "Malagasy Ariary"},
	"MWK": {Alpha3: "MWK", Numeric: 454, MinorUnits: 2, Name: "Malawi Kwacha"},
	"MYR": {Alpha3: "MYR", Numeric: 458, MinorUnits: 2, Name: "Malaysian Ringgit"},
	"MVR": {Alpha3: "MVR", Numeric: 462, MinorUnits: 2, Name: "Rufiyaa"},
	"MRU": {Alpha3: "MRU", Numeric: 929, MinorUnits: 2, Name: "Ouguiya"},
	"MUR": {Alpha3: "MUR", Numeric: 480, MinorUnits: 2, Name: "Mauritius Rupee"},
	"XUA": {Alpha3: "XUA", Numeric: 965, MinorUnits: -1, Name: "ADB Unit of Account"},
	"MXN": {Alpha3: "MXN", Numeric: 484, MinorUnits: 2, Name: "Mexican Peso"},
	"MXV": {Alpha3: "MXV", Numeric: 979, MinorUnits: 2, Name: "Mexican Unidad de Inversion (UDI)"},
	"MDL": {Alpha3: "MDL", Numeric: 498, MinorUnits: 2, Name: "Moldovan Leu"},
	"MNT": {Alpha3: "MNT", Numeric: 496, MinorUnits: 2, Name: "Tugrik"},
	"MAD": {Alpha3: "MAD", Numeric: 504, MinorUnits: 2, Name: "Moroccan Dirham"},
	"MZN": {Alpha3: "MZN", Numeric: 943, MinorUnits: 2, Name: "Mozambique Metical"},
	"MMK": {Alpha3: "MMK", Numeric: 104, MinorUnits: 2, Name: "Kyat"},
	"NAD": {Alpha3: "NAD", Numeric: 516, MinorUnits: 2, Name: "Namibia Dollar"},
	"NPR": {Alpha3: "NPR", Numeric: 524, MinorUnits: 2, Name: "Nepalese Rupee"},
	"NIO": {Alpha3: "NIO", Numeric: 558, MinorUnits: 2, Name: "Cordoba Oro"},
	"NGN": {Alpha3: "NGN", Numeric: 566, MinorUnits: 2, Name: "Naira"},
	"OMR": {Alpha3: "OMR", Numeric: 512, MinorUnits: 3, Name: "Rial Omani"},
	"PKR": {Alpha3: "PKR", Numeric: 586, MinorUnits: 2, Name: "Pakistan Rupee"},
	"PAB": {Alpha3: "PAB", Numeric: 590, MinorUnits: 2, Name: "Balboa"},
	"PGK": {Alpha3: "PGK", Numeric: 598, MinorUnits: 2, Name: "Kina"},
	"PYG": {Alpha3: "PYG", Numeric: 600, MinorUnits: 0, Name: "Guarani"},
	"PEN": {Alpha3: "PEN", Numeric: 604, MinorUnits: 2, Name: "Sol"},
	"PHP": {Alpha3: "PHP", Numeric: 608, MinorUnits: 2, Name: "Philippine Peso"},
	"PLN": {Alpha3: "PLN", Numeric: 985, MinorUnits: 2, Name: "Zloty"},
	"QAR": {Alpha3: "QAR", Numeric: 634, MinorUnits: 2, Name: "Qatari Rial"},
	"RON": {Alpha3: "RON", Numeric: 946, MinorUnits: 2, Name: "Romanian Leu"},
	"RUB": {Alpha3: "RUB", Numeric: 643, MinorUnits: 2, Name: "Russian Ruble"},
	"RWF": {Alpha3: "RWF", Numeric: 646, MinorUnits: 0, Name: "Rwanda Franc"},
	"SHP": {Alpha3: "SHP", Numeric: 654, MinorUnits: 2, Name: "Saint Helena Pound"},
	"WST": {Alpha3: "WST", Numeric: 882, MinorUnits: 2, Name: "Tala"},
	"STN": {Alpha3: "STN", Numeric: 930, MinorUnits: 2, Name: "Dobra"},
	"SAR": {Alpha3: "SAR", Numeric: 682, MinorUnits: 2, Name: "Saudi Riyal"},
	"RSD": {Alpha3: "RSD", Numeric: 941, MinorUnits: 2, Name: "Serbian Dinar"},
	"SCR": {Alpha3: "SCR", Numeric: 690, MinorUnits: 2, Name: "Seychelles Rupee"},
	"SLE": {Alpha3: "SLE", Numeric: 925, MinorUnits: 2, Name: "Leone"},
	"SGD": {Alpha3: "SGD", Numeric: 702, MinorUnits: 2, Name: "Singapore Dollar"},
	"XSU": {Alpha3: "XSU", Numeric: 994, MinorUnits: -1, Name: "Sucre"},
	"SBD": {Alpha3: "SBD", Numeric: 90, MinorUnits: 2, Name: "Solomon Islands Dollar"},
	"SOS": {Alpha3: "SOS", Numeric: 706, MinorUnits: 2, Name: "Somali Shilling"},
	"SSP": {Alpha3: "SSP", Numeric: 728, MinorUnits: 2, Name: "South Sudanese Pound"},
	"LKR": {Alpha3: "LKR", Numeric: 144, MinorUnits: 2, Name: "Sri Lanka Rupee"},
	"SDG": {Alpha3: "SDG", Numeric: 938, MinorUnits: 2, Name: "Sudanese Pound"},
	"SRD": {Alpha3: "SRD", Numeric: 968, MinorUnits: 2, Name: "Surinam Dollar"},
	"SEK": {Alpha3: "SEK", Numeric: 752, MinorUnits: 2, Name: "Swedish Krona"},
	"CHE": {Alpha3: "CHE", Numeric: 947, MinorUnits: 2, Name: "WIR Euro"},
	"CHW": {Alpha3: "CHW", Numeric: 948, MinorUnits: 2, Name: "WIR Franc"},
	"SYP": {Alpha3: "SYP", Numeric: 760, MinorUnits: 2, Name: "Syrian Pound"},
	"TWD": {Alpha3: "TWD", Numeric: 901, MinorUnits: 2, Name: "New Taiwan Dollar"},
	"TJS": {Alpha3: "TJS", Numeric: 972, MinorUnits: 2, Name: "Somoni"},
	"TZS": {Alpha3: "TZS", Numeric: 834, MinorUnits: 2, Name: "Tanzanian Shilling"},
	"THB": {Alpha3: "THB", Numeric: 764, MinorUnits: 2, Name: "Baht"},
	"TOP": {Alpha3: "TOP", Numeric: 776, MinorUnits: 2, Name: "Pa’anga"},
	"TTD": {Alpha3: "TTD", Numeric: 780, MinorUnits: 2, Name: "Trinidad and Tobago Dollar"},
	"TND": {Alpha3: "TND", Numeric: 788, MinorUnits: 3, Name: "Tunisian Dinar"},
	"TRY": {Alpha3: "TRY", Numeric: 949, MinorUnits: 2, Name: "Turkish Lira"},
	"TMT": {Alpha3: "TMT", Numeric: 934, MinorUnits: 2, Name: "Turkmenistan New Manat"},
	"UGX": {Alpha3: "UGX", Numeric: 800, MinorUnits: 0, Name: "Uganda Shilling"},
	"UAH": {Alpha3: "UAH", Numeric: 980, MinorUnits: 2, Name: "Hryvnia"},
	"AED": {Alpha3: "AED", Numeric: 784, MinorUnits: 2, Name: "UAE Dirham"},
	"USN": {Alpha3: "USN", Numeric: 997, MinorUnits: 2, Name: "US Dollar (Next day)"},
	"UYU": {Alpha3: "UYU", Numeric: 858, MinorUnits: 2, Name: "Peso Uruguayo"},
	"UYI": {Alpha3: "UYI", Numeric: 940, MinorUnits: 0, Name: "Uruguay Peso en Unidades Indexadas (UI)"},
	"UYW": {Alpha3: "UYW", Numeric: 927, MinorUnits: 4, Name: "Unidad Previsional"},
	"UZS": {Alpha3: "UZS", Numeric: 860, MinorUnits: 2, Name: "Uzbekistan Sum"},
	"VUV": {Alpha3: "VUV", Numeric: 548, MinorUnits: 0, Name: "Vatu"},
	"VES": {Alpha3: "VES", Numeric: 928, MinorUnits: 2, Name: "Bolívar Soberano"},
	"VED": {Alpha3: "VED", Numeric: 926, MinorUnits: 2, Name: "Bolívar Soberano"},
	"VND": {Alpha3: "VND", Numeric: 704, MinorUnits: 0, Name: "Dong"},
	"YER": {Alpha3: "YER", Numeric: 886, MinorUnits: 2, Name: "Yemeni Rial"},
	"ZMW": {Alpha3: "ZMW", Numeric: 967, MinorUnits: 2, Name: "Zambian Kwacha"},
	"ZWG": {Alpha3: "ZWG", Numeric: 924, MinorUnits: 2, Name: "Zimbabwe Gold"},
	"XBA": {Alpha3: "XBA", Numeric: 955, MinorUnits: -1, Name: "Bond Markets Unit European Composite Unit (EURCO)"},
	"XBB": {Alpha3: "XBB", Numeric: 956, MinorUnits: -1, Name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)"},
	"XBC": {Alpha3: "XBC", Numeric: 957, MinorUnits: -1, Name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"},
	"XBD": {Alpha3: "XBD", Numeric: 958, MinorUnits: -1, Name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"},
	"XTS": {Alpha3: "XTS", Numeric: 963, MinorUnits: -1, Name: "Codes specifically reserved for testing purposes"},
	"XXX": {Alpha3: "XXX", Numeric: 999, MinorUnits: -1, Name: "The codes assigned for transactions where no currency is involved"},
	"XAU": {Alpha3: "XAU", Numeric: 959, MinorUnits: -1, Name: "Gold"},
	"XPD": {Alpha3: "XPD", Numeric: 964, MinorUnits: -1, Name: "Palladium"},
	"XPT": {Alpha3: "XPT", Numeric: 962, MinorUnits: -1, Name: "Platinum"},
	"XAG": {Alpha3: "XAG", Numeric: 961, MinorUnits: -1, Name: "Silver"},
}

var currenciesByNumeric = map[int]Currency{
	971: {Alpha3: "AFN", Numeric: 971, MinorUnits: 2, Name: "Afghani"},
	978: {Alpha3: "EUR", Numeric: 978, MinorUnits: 2, Name: "Euro"},
	8: {Alpha3: "ALL", Numeric: 8, MinorUnits: 2, Name: "Lek"},
	12: {Alpha3: "DZD", Numeric: 12, MinorUnits: 2, Name: "Algerian Dinar"},
	840: {Alpha3: "USD", Numeric: 840, MinorUnits: 2, Name: "US Dollar"},
	973: {Alpha3: "AOA", Numeric: 973, MinorUnits: 2, Name: "Kwanza"},
	951: {Alpha3: "XCD", Numeric: 951, MinorUnits: 2, Name: "East Caribbean Dollar"},
	396: {Alpha3: "XAD", Numeric: 396, MinorUnits: 2, Name: "Arab Accounting Dinar"},
	32: {Alpha3: "ARS", Numeric: 32, MinorUnits: 2, Name: "Argentine Peso"},
	51: {Alpha3: "AMD", Numeric: 51, MinorUnits: 2, Name: "Armenian Dram"},
	533: {Alpha3: "AWG", Numeric: 533, MinorUnits: 2, Name: "Aruban Florin"},
	36: {Alpha3: "AUD", Numeric: 36, MinorUnits: 2, Name: "Australian Dollar"},
	944: {Alpha3: "AZN", Numeric: 944, MinorUnits: 2, Name: "Azerbaijan Manat"},
	44: {Alpha3: "BSD", Numeric: 44, MinorUnits: 2, Name: "Bahamian Dollar"},
	48: {Alpha3: "BHD", Numeric: 48, MinorUnits: 3, Name: "Bahraini Dinar"},
	50: {Alpha3: "BDT", Numeric: 50, MinorUnits: 2, Name: "Taka"},
	52: {Alpha3: "BBD", Numeric: 52, MinorUnits: 2, Name: "Barbados Dollar"},
	933: {Alpha3: "BYN", Numeric: 933, MinorUnits: 2, Name: "Belarusian Ruble"},
	84: {Alpha3: "BZD", Numeric: 84, MinorUnits: 2, Name: "Belize Dollar"},
	952: {Alpha3: "XOF", Numeric: 952, MinorUnits: 0, Name: "CFA Franc BCEAO"},
	60: {Alpha3: "BMD", Numeric: 60, MinorUnits: 2, Name: "Bermudian Dollar"},
	356: {Alpha3: "INR", Numeric: 356, MinorUnits: 2, Name: "Indian Rupee"},
	64: {Alpha3: "BTN", Numeric: 64, MinorUnits: 2, Name: "Ngultrum"},
	68: {Alpha3: "BOB", Numeric: 68, MinorUnits: 2, Name: "Boliviano"},
	984: {Alpha3: "BOV", Numeric: 984, MinorUnits: 2, Name: "Mvdol"},
	977: {Alpha3: "BAM", Numeric: 977, MinorUnits: 2, Name: "Convertible Mark"},
	72: {Alpha3: "BWP", Numeric: 72, MinorUnits: 2, Name: "Pula"},
	578: {Alpha3: "NOK", Numeric: 578, MinorUnits: 2, Name: "Norwegian Krone"},
	986: {Alpha3: "BRL", Numeric: 986, MinorUnits: 2, Name: "Brazilian Real"},
	96: {Alpha3: "BND", Numeric: 96, MinorUnits: 2, Name: "Brunei Dollar"},
	975: {Alpha3: "BGN", Numeric: 975, MinorUnits: 2, Name: "Bulgarian Lev"},
	108: {Alpha3: "BIF", Numeric: 108, MinorUnits: 0, Name: "Burundi Franc"},
	132: {Alpha3: "CVE", Numeric: 132, MinorUnits: 2, Name: "Cabo Verde Escudo"},
	116: {Alpha3: "KHR", Numeric: 116, MinorUnits: 2, Name: "Riel"},
	950: {Alpha3: "XAF", Numeric: 950, MinorUnits: 0, Name: "CFA Franc BEAC"},
	124: {Alpha3: "CAD", Numeric: 124, MinorUnits: 2, Name: "Canadian Dollar"},
	136: {Alpha3: "KYD", Numeric: 136, MinorUnits: 2, Name: "Cayman Islands Dollar"},
	152: {Alpha3: "CLP", Numeric: 152, MinorUnits: 0, Name: "Chilean Peso"},
	990: {Alpha3: "CLF", Numeric: 990, MinorUnits: 4, Name: "Unidad de Fomento"},
	156: {Alpha3: "CNY", Numeric: 156, MinorUnits: 2, Name: "Yuan Renminbi"},
	170: {Alpha3: "COP", Numeric: 170, MinorUnits: 2, Name: "Colombian Peso"},
	970: {Alpha3: "COU", Numeric: 970, MinorUnits: 2, Name: "Unidad de Valor Real"},
	174: {Alpha3: "KMF", Numeric: 174, MinorUnits: 0, Name: "Comorian Franc "},
	976: {Alpha3: "CDF", Numeric: 976, MinorUnits: 2, Name: "Congolese Franc"},
	554: {Alpha3: "NZD", Numeric: 554, MinorUnits: 2, Name: "New Zealand Dollar"},
	188: {Alpha3: "CRC", Numeric: 188, MinorUnits: 2, Name: "Costa Rican Colon"},
	192: {Alpha3: "CUP", Numeric: 192, MinorUnits: 2, Name: "Cuban Peso"},
	532: {Alpha3: "XCG", Numeric: 532, MinorUnits: 2, Name: "Caribbean Guilder"},
	203: {Alpha3: "CZK", Numeric: 203, MinorUnits: 2, Name: "Czech Koruna"},
	208: {Alpha3: "DKK", Numeric: 208, MinorUnits: 2, Name: "Danish Krone"},
	262: {Alpha3: "DJF", Numeric: 262, MinorUnits: 0, Name: "Djibouti Franc"},
	214: {Alpha3: "DOP", Numeric: 214, MinorUnits: 2, Name: "Dominican Peso"},
	818: {Alpha3: "EGP", Numeric: 818, MinorUnits: 2, Name: "Egyptian Pound"},
	222: {Alpha3: "SVC", Numeric: 222, MinorUnits: 2, Name: "El Salvador Colon"},
	232: {Alpha3: "ERN", Numeric: 232, MinorUnits: 2, Name: "Nakfa"},
	748: {Alpha3: "SZL", Numeric: 748, MinorUnits: 2, Name: "Lilangeni"},
	230: {Alpha3: "ETB", Numeric: 230, MinorUnits: 2, Name: "Ethiopian Birr"},
	238: {Alpha3: "FKP", Numeric: 238, MinorUnits: 2, Name: "Falkland Islands Pound"},
	242: {Alpha3: "FJD", Numeric: 242, MinorUnits: 2, Name: "Fiji Dollar"},
	953: {Alpha3: "XPF", Numeric: 953, MinorUnits: 0, Name: "CFP Franc"},
	270: {Alpha3: "GMD", Numeric: 270, MinorUnits: 2, Name: "Dalasi"},
	981: {Alpha3: "GEL", Numeric: 981, MinorUnits: 2, Name: "Lari"},
	936: {Alpha3: "GHS", Numeric: 936, MinorUnits: 2, Name: "Ghana Cedi"},
	292: {Alpha3: "GIP", Numeric: 292, MinorUnits: 2, Name: "Gibraltar Pound"},
	320: {Alpha3: "GTQ", Numeric: 320, MinorUnits: 2, Name: "Quetzal"},
	826: {Alpha3: "GBP", Numeric: 826, MinorUnits: 2, Name: "Pound Sterling"},
	324: {Alpha3: "GNF", Numeric: 324, MinorUnits: 0, Name: "Guinean Franc"},
	328: {Alpha3: "GYD", Numeric: 328, MinorUnits: 2, Name: "Guyana Dollar"},
	332: {Alpha3: "HTG", Numeric: 332, MinorUnits: 2, Name: "Gourde"},
	340: {Alpha3: "HNL", Numeric: 340, MinorUnits: 2, Name: "Lempira"},
	344: {Alpha3: "HKD", Numeric: 344, MinorUnits: 2, Name: "Hong Kong Dollar"},
	348: {Alpha3: "HUF", Numeric: 348, MinorUnits: 2, Name: "Forint"},
	352: {Alpha3: "ISK", Numeric: 352, MinorUnits: 0, Name: "Iceland Krona"},
	360: {Alpha3: "IDR", Numeric: 360, MinorUnits: 2, Name: "Rupiah"},
	960: {Alpha3: "XDR", Numeric: 960, MinorUnits: -1, Name: "SDR (Special Drawing Right)"},
	364: {Alpha3: "IRR", Numeric: 364, MinorUnits: 2, Name: "Iranian Rial"},
	368: {Alpha3: "IQD", Numeric: 368, MinorUnits: 3, Name: "Iraqi Dinar"},
	376: {Alpha3: "ILS", Numeric: 376, MinorUnits: 2, Name: "New Israeli Sheqel"},
	388: {Alpha3: "JMD", Numeric: 388, MinorUnits: 2, Name: "Jamaican Dollar"},
	392: {Alpha3: "JPY", Numeric: 392, MinorUnits: 0, Name: "Yen"},
	400: {Alpha3: "JOD", Numeric: 400, MinorUnits: 3, Name: "Jordanian Dinar"},
	398: {Alpha3: "KZT", Numeric: 398, MinorUnits: 2, Name: "Tenge"},
	404: {Alpha3: "KES", Numeric: 404, MinorUnits: 2, Name: "Kenyan Shilling"},
	408: {Alpha3: "KPW", Numeric: 408, MinorUnits: 2, Name: "North Korean Won"},
	410: {Alpha3: "KRW", Numeric: 410, MinorUnits: 0, Name: "Won"},
	414: {Alpha3: "KWD", Numeric: 414, MinorUnits: 3, Name: "Kuwaiti Dinar"},
	417: {Alpha3: "KGS", Numeric: 417, MinorUnits: 2, Name: "Som"},
	418: {Alpha3: "LAK", Numeric: 418, MinorUnits: 2, Name: "Lao Kip"},
	422: {Alpha3: "LBP", Numeric: 422, MinorUnits: 2, Name: "Lebanese Pound"},
	426: {Alpha3: "LSL", Numeric: 426, MinorUnits: 2, Name: "Loti"},
	710: {Alpha3: "ZAR", Numeric: 710, MinorUnits: 2, Name: "Rand"},
	430: {Alpha3: "LRD", Numeric: 430, MinorUnits: 2, Name: "Liberian Dollar"},
	434: {Alpha3: "LYD", Numeric: 434, MinorUnits: 3, Name: "Libyan Dinar"},
	756: {Alpha3: "CHF", Numeric: 756, MinorUnits: 2, Name: "Swiss Franc"},
	446: {Alpha3: "MOP", Numeric: 446, MinorUnits: 2, Name: "Pataca"},
	807: {Alpha3: "MKD", Numeric: 807, MinorUnits: 2, Name: "Denar"},
	969: {Alpha3: "MGA", Numeric: 969, MinorUnits: 2, Name: "Malagasy Ariary"},
	454: {Alpha3: "MWK", Numeric: 454, MinorUnits: 2, Name: "Malawi Kwacha"},
	458: {Alpha3: "MYR", Numeric: 458, MinorUnits: 2, Name: "Malaysian Ringgit"},
	462: {Alpha3: "MVR", Numeric: 462, MinorUnits: 2, Name: "Rufiyaa"},
	929: {Alpha3: "MRU", Numeric: 929, MinorUnits: 2, Name: "Ouguiya"},
	480: {Alpha3: "MUR", Numeric: 480, MinorUnits: 2, Name: "Mauritius Rupee"},
	965: {Alpha3: "XUA", Numeric: 965, MinorUnits: -1, Name: "ADB Unit of Account"},
	484: {Alpha3: "MXN", Numeric: 484, MinorUnits: 2, Name: "Mexican Peso"},
	979: {Alpha3: "MXV", Numeric: 979, MinorUnits: 2, Name: "Mexican Unidad de Inversion (UDI)"},
	498: {Alpha3: "MDL", Numeric: 498, MinorUnits: 2, Name: "Moldovan Leu"},
	496: {Alpha3: "MNT", Numeric: 496, MinorUnits: 2, Name: "Tugrik"},
	504: {Alpha3: "MAD", Numeric: 504, MinorUnits: 2, Name: "Moroccan Dirham"},
	943: {Alpha3: "MZN", Numeric: 943, MinorUnits: 2, Name: "Mozambique Metical"},
	104: {Alpha3: "MMK", Numeric: 104, MinorUnits: 2, Name: "Kyat"},
	516: {Alpha3: "NAD", Numeric: 516, MinorUnits: 2, Name: "Namibia Dollar"},
	524: {Alpha3: "NPR", Numeric: 524, MinorUnits: 2, Name: "Nepalese Rupee"},
	558: {Alpha3: "NIO", Numeric: 558, MinorUnits: 2, Name: "Cordoba Oro"},
	566: {Alpha3: "NGN", Numeric: 566, MinorUnits: 2, Name: "Naira"},
	512: {Alpha3: "OMR", Numeric: 512, MinorUnits: 3, Name: "Rial Omani"},
	586: {Alpha3: "PKR", Numeric: 586, MinorUnits: 2, Name: "Pakistan Rupee"},
	590: {Alpha3: "PAB", Numeric: 590, MinorUnits: 2, Name: "Balboa"},
	598: {Alpha3: "PGK", Numeric: 598, MinorUnits: 2, Name: "Kina"},
	600: {Alpha3: "PYG", Numeric: 600, MinorUnits: 0, Name: "Guarani"},
	604: {Alpha3: "PEN", Numeric: 604, MinorUnits: 2, Name: "Sol"},
	608: {Alpha3: "PHP", Numeric: 608, MinorUnits: 2, Name: "Philippine Peso"},
	985: {Alpha3: "PLN", Numeric: 985, MinorUnits: 2, Name: "Zloty"},
	634: {Alpha3: "QAR", Numeric: 634, MinorUnits: 2, Name: "Qatari Rial"},
	946: {Alpha3: "RON", Numeric: 946, MinorUnits: 2, Name: "Romanian Leu"},
	643: {Alpha3: "RUB", Numeric: 643, MinorUnits: 2, Name: "Russian Ruble"},
	646: {Alpha3: "RWF", Numeric: 646, MinorUnits: 0, Name: "Rwanda Franc"},
	654: {Alpha3: "SHP", Numeric: 654, MinorUnits: 2, Name: "Saint Helena Pound"},
	882: {Alpha3: "WST", Numeric: 882, MinorUnits: 2, Name: "Tala"},
	930: {Alpha3: "STN", Numeric: 930, MinorUnits: 2, Name: "Dobra"},
	682: {Alpha3: "SAR", Numeric: 682, MinorUnits: 2, Name: "Saudi Riyal"},
	941: {Alpha3: "RSD", Numeric: 941, MinorUnits: 2, Name: "Serbian Dinar"},
	690: {Alpha3: "SCR", Numeric: 690, MinorUnits: 2, Name: "Seychelles Rupee"},
	925: {Alpha3: "SLE", Numeric: 925, MinorUnits: 2, Name: "Leone"},
	702: {Alpha3: "SGD", Numeric: 702, MinorUnits: 2, Name: "Singapore Dollar"},
	994: {Alpha3: "XSU", Numeric: 994, MinorUnits: -1, Name: "Sucre"},
	90: {Alpha3: "SBD", Numeric: 90, MinorUnits: 2, Name: "Solomon Islands Dollar"},
	706: {Alpha3: "SOS", Numeric: 706, MinorUnits: 2, Name: "Somali Shilling"},
	728: {Alpha3: "SSP", Numeric: 728, MinorUnits: 2, Name: "South Sudanese Pound"},
	144: {Alpha3: "LKR", Numeric: 144, MinorUnits: 2, Name: "Sri Lanka Rupee"},
	938: {Alpha3: "SDG", Numeric: 938, MinorUnits: 2, Name: "Sudanese Pound"},
	968: {Alpha3: "SRD", Numeric: 968, MinorUnits: 2, Name: "Surinam Dollar"},
	752: {Alpha3: "SEK", Numeric: 752, MinorUnits: 2, Name: "Swedish Krona"},
	947: {Alpha3: "CHE", Numeric: 947, MinorUnits: 2, Name: "WIR Euro"},
	948: {Alpha3: "CHW", Numeric: 948, MinorUnits: 2, Name: "WIR Franc"},
	760: {Alpha3: "SYP", Numeric: 760, MinorUnits: 2, Name: "Syrian Pound"},
	901: {Alpha3: "TWD", Numeric: 901, MinorUnits: 2, Name: "New Taiwan Dollar"},
	972: {Alpha3: "TJS", Numeric: 972, MinorUnits: 2, Name: "Somoni"},
	834: {Alpha3: "TZS", Numeric: 834, MinorUnits: 2, Name: "Tanzanian Shilling"},
	764: {Alpha3: "THB", Numeric: 764, MinorUnits: 2, Name: "Baht"},
	776: {Alpha3: "TOP", Numeric: 776, MinorUnits: 2, Name: "Pa’anga"},
	780: {Alpha3: "TTD", Numeric: 780, MinorUnits: 2, Name: "Trinidad and Tobago Dollar"},
	788: {Alpha3: "TND", Numeric: 788, MinorUnits: 3, Name: "Tunisian Dinar"},
	949: {Alpha3: "TRY", Numeric: 949, MinorUnits: 2, Name: "Turkish Lira"},
	934: {Alpha3: "TMT", Numeric: 934, MinorUnits: 2, Name: "Turkmenistan New Manat"},
	800: {Alpha3: "UGX", Numeric: 800, MinorUnits: 0, Name: "Uganda Shilling"},
	980: {Alpha3: "UAH", Numeric: 980, MinorUnits: 2, Name: "Hryvnia"},
	784: {Alpha3: "AED", Numeric: 784, MinorUnits: 2, Name: "UAE Dirham"},
	997: {Alpha3: "USN", Numeric: 997, MinorUnits: 2, Name: "US Dollar (Next day)"},
	858: {Alpha3: "UYU", Numeric: 858, MinorUnits: 2, Name: "Peso Uruguayo"},
	940: {Alpha3: "UYI", Numeric: 940, MinorUnits: 0, Name: "Uruguay Peso en Unidades Indexadas (UI)"},
	927: {Alpha3: "UYW", Numeric: 927, MinorUnits: 4, Name: "Unidad Previsional"},
	860: {Alpha3: "UZS", Numeric: 860, MinorUnits: 2, Name: "Uzbekistan Sum"},
	548: {Alpha3: "VUV", Numeric: 548, MinorUnits: 0, Name: "Vatu"},
	928: {Alpha3: "VES", Numeric: 928, MinorUnits: 2, Name: "Bolívar Soberano"},
	926: {Alpha3: "VED", Numeric: 926, MinorUnits: 2, Name: "Bolívar Soberano"},
	704: {Alpha3: "VND", Numeric: 704, MinorUnits: 0, Name: "Dong"},
	886: {Alpha3: "YER", Numeric: 886, MinorUnits: 2, Name: "Yemeni Rial"},
	967: {Alpha3: "ZMW", Numeric: 967, MinorUnits: 2, Name: "Zambian Kwacha"},
	924: {Alpha3: "ZWG", Numeric: 924, MinorUnits: 2, Name: "Zimbabwe Gold"},
	955: {Alpha3: "XBA", Numeric: 955, MinorUnits: -1, Name: "Bond Markets Unit European Composite Unit (EURCO)"},
	956: {Alpha3: "XBB", Numeric: 956, MinorUnits: -1, Name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)"},
	957: {Alpha3: "XBC", Numeric: 957, MinorUnits: -1, Name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"},
	958: {Alpha3: "XBD", Numeric: 958, MinorUnits: -1, Name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"},
	963: {Alpha3: "XTS", Numeric: 963, MinorUnits: -1, Name: "Codes specifically reserved for testing purposes"},
	999: {Alpha3: "XXX", Numeric: 999, MinorUnits: -1, Name: "The codes assigned for transactions where no currency is involved"},
	959: {Alpha3: "XAU", Numeric: 959, MinorUnits: -1, Name: "Gold"},
	964: {Alpha3: "XPD", Numeric: 964, MinorUnits: -1, Name: "Palladium"},
	962: {Alpha3: "XPT", Numeric: 962, MinorUnits: -1, Name: "Platinum"},
	961: {Alpha3: "XAG", Numeric: 961, MinorUnits: -1, Name: "Silver"},
}
